### ISSUE TITLE
Tic Tac Toe Game Project

### ISSUE THREAD

**Issue by AniketP04** [laviii123/Btecky#262]
I have implemented it using HTML, CSS and Javascript.

Can i add this project??

If yes, Please assign this issue to me.

**Comment by sourav2210** [comment]
could you please assign this project to me.
I can do this project by using Java AWT framework.
if yes, please assign me.

**Comment by Naveen01S** [comment]
I can do this project by using html css js. & python alsoo
Can I add this project?
If yes , please assign me🙌🏻

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.
